### ISSUE TITLE
Change mime type for jsonp

### ISSUE THREAD

**Issue by fullergalway** [BobSimons/erddap#16]
Chrome browser gives an error for the mime type returned for a jsonp request.

> Refused to execute script from 'https://erddap.marine.ie/erddap/tabledap/IWBNetwork.json?longitude,latitude,time,station_id&time%3E=2018-01-08T09:53:33.009Z&station_id=%22M4%22&.jsonp=jQuery20308886091928996869_1515413372716' because its MIME type ('application/json') is not executable, and strict MIME type checking is enabled.

(MIME type should be 'application/javascript' if the json is requested and .jsonp flag is set)

https://stackoverflow.com/questions/477816/what-is-the-correct-json-content-type

**Comment by BobSimons** [comment]
That sounds like a good idea.
I will try to make the change in the version of ERDDAP that I am working on.

**Comment by BobSimons** [comment]
That change is now available in ERDDAP v1.82.
Thanks again for the suggestion.
