### ISSUE TITLE
Meta enhancement for search engine indexing

### ISSUE THREAD

**Issue by fullergalway** [BobSimons/erddap#18]
Consider adding rel="next" and rel="prev" links on the index page
[https://support.google.com/webmasters/answer/1663744?hl=en&ref_topic=4617741](https://support.google.com/webmasters/answer/1663744?hl=en&ref_topic=4617741)

for example in the head of the page here:
[http://coastwatch.pfeg.noaa.gov/erddap/info/index.html?page=1&itemsPerPage=3](http://coastwatch.pfeg.noaa.gov/erddap/info/index.html?page=1&itemsPerPage=3)

**Comment by BobSimons** [comment]
This is an excellent idea. I'm surprised rel="next" and "prev" weren't already used.
I have made the change. It will be in the next release: v1.84.
Thank you very much for suggesting this.

**Comment by fullergalway** [comment]
This is done. Thanks Bob! Marking as closed.
