### ISSUE TITLE
File descriptor leak

### ISSUE THREAD

**Issue by jibeizhao** [BobSimons/erddap#20]
When a user queries for image data in ERDDAP, the file descriptor is left open indefinitely until max limit is reached. File is deleted, but handler is left open.

**Comment by jibeizhao** [comment]
Noticed this while we were querying geotiff files, the server would crash after querying for too many geotiffs.
I checked the codes, it seems the saveAsGeotiff function did close the writer, didn't dig deeper.
Could you have a look at this?

Thx

**Comment by BobSimons** [comment]
Thanks for letting me know. I will investigate.

**Comment by jibeizhao** [comment]
Fixed in the newer version

**Comment by BobSimons** [comment]
Good. Thanks for confirming this.
