### ISSUE TITLE
baseUrl

### ISSUE THREAD

**Issue by Nilster** [BobSimons/erddap#27]
Hi,

Is there any way not to hardcode baseUrl in the setup file? As far as I can see, you have to specify baseUrl. I would like the request to continue with with the whatever url Tomcat is referencing to how can I achieve this?

**Comment by Nilster** [comment]
Just discovered that setting the <baseUrl>/.</baseUrl>  tag gets around this issue. Sorry about the confusion.

**Comment by BobSimons** [comment]
I don't understand. Can you please tell me more about /. and how it gets around this issue?
Thanks.

**Comment by Nilster** [comment]
I am not exactly sure how it works inside the ERDDAP app but after playing around with the url paths this combination worked for me. [https://stackoverflow.com/questions/24028561/relative-path-in-html](url) prompted me to try out this combination.
