### ISSUE TITLE
Unzip  erddap code error

### ISSUE THREAD

**Issue by shiuliu** [BobSimons/erddap#28]
erddap code downloaded successfully,but unzip error. help me .thank you!

**Comment by BobSimons** [comment]
What file did you download?  
From where did you download it?
What was the software you used to unzip the file?
What was the error message?

The most likely thing is that the file didn't download correctly. Please rename the file you downloaded and download the file from the source again.

**Comment by shiuliu** [comment]
download incorrect，thank you
