### ISSUE TITLE
erddap graph feature plotting NaN points

### ISSUE THREAD

**Issue by emmerbodc** [BobSimons/erddap#31]
Hello, 
At BODC we have loaded a discrete water samples dataset - 
https://linkedsystems.uk/erddap/tabledap/samples_cobs_20200901.html

The original data is stored in BODC in a relational database so to pull it together we created a denormalized view so the data are sparse now. 

We haven't assigned a fill value, leaving it at NaN as they don't exist in the relational database. However we noticed on the html download these are blank which is fine but on the graph feature, it is plotting these points (greyed out). 

Please see - 
https://linkedsystems.uk/erddap/tabledap/samples_cobs_20200901.graph?time%2Cdepth%2CPHOSAATX&time%3E=2002-08-07T11%3A34%3A39Z&time%3C=2011-11-10T00%3A00%3A00Z&longitude%3E=-4.094&longitude%3C=-2.923&latitude%3E=53.008&latitude%3C=54.18&.draw=markers&.marker=1%7C5&.color=0xFFFFFF&.colorBar=%7C%7C%7C0%7C2%7C&.bgColor=0xffccccff

I can only get rid of the grey points by adding the parameter as a contraint which i'm not sure is all that intuitive for an end user. Would it be possible for the graphing feature to exclude NaNs on the plot?

https://linkedsystems.uk/erddap/tabledap/samples_cobs_20200901.graph?time%2Cdepth%2CPHOSAATX&time%3E=2002-08-07T11%3A34%3A39Z&time%3C=2011-11-10T00%3A00%3A00Z&longitude%3E=-4.094&longitude%3C=-2.923&latitude%3E=53.008&latitude%3C=54.18&PHOSAATX%3E=0&PHOSAATX%3C=10&.draw=markers&.marker=1%7C5&.color=0xFFFFFF&.colorBar=%7C%7C%7C0%7C2.5%7C&.bgColor=0xffccccff

Thanks,
Emma 
British Oceanographic Data Centre

**Comment by BobSimons** [comment]
Isn't the desired feature: &_varName_!=NaN (as you point out)?
It has the desired functionality and it uses the existing constraints system.

More features add to the complexity of the web page, the request, and the code. If the new feature isn't necessary because there is already a decent solution, I am reluctant to add the new feature.

It's true that it may not be obvious to an end user.

**Comment by emmerbodc** [comment]
ok thanks.
