### ISSUE TITLE
ERDDAP TrajectoryProfile issue. 

### ISSUE THREAD

**Issue by cyhsu** [BobSimons/erddap#33]
Question: In the DMAC meeting today, I addressed issues that are related to the Trajectory Profile dataset. One of the questions is the IOOS compliance checker - NCEI Trajectory Profile Orthogonal 2.0 is asking the Trajectory Profile netCDF file has set "cdm_data_type" = "Trajectory" and then set "featureType" = "trajectoryProfile," while in ERDDAP, it is saying "cdm_data_type" = "TrajectoryProfile". Another question is if I use the [**standard NCEI Trajectory Profile** example netCDF file](https://data.nodc.noaa.gov/thredds/catalog/example/v2.0/catalog.html?dataset=example/v2.0/NCEI_trajectoryProfile_template_v2.0_2016-09-22_181838.014029.nc), and feed the file into the ERDDAP directly, with slight modification (set global attribute **cdm_trajectory_variables = trajectory**), the ERDDAP will provide the error to me, 

`*** An error occurred while trying to load NCEI_R4_23e3_15d9_6c01:
java.lang.RuntimeException: datasets.xml error on or before line #286: cdm_data_type=Trajectory, but the dataset doesn't have a longitude variable.
 at gov.noaa.pfel.erddap.dataset.EDD.fromXml(EDD.java:436)
 at gov.noaa.pfel.erddap.dataset.EDD.oneFromDatasetsXml(EDD.java:517)
 at gov.noaa.pfel.erddap.dataset.EDD.testDasDds(EDD.java:11068)
 at gov.noaa.pfel.erddap.DasDds.doIt(DasDds.java:129)
 at gov.noaa.pfel.erddap.DasDds.main(DasDds.java:155)
Caused by: com.cohort.util.SimpleException: cdm_data_type=Trajectory, but the dataset doesn't have a longitude variable.
 at gov.noaa.pfel.erddap.dataset.EDDTable.accessibleViaNcCF(EDDTable.java:13105)
 at gov.noaa.pfel.erddap.dataset.EDD.ensureValid(EDD.java:770)
 at gov.noaa.pfel.erddap.dataset.EDDTable.ensureValid(EDDTable.java:612)
 at gov.noaa.pfel.erddap.dataset.EDDTableFromFiles.<init>(EDDTableFromFiles.java:1839)
 at gov.noaa.pfel.erddap.dataset.EDDTableFromNcFiles.<init>(EDDTableFromNcFiles.java:128)
 at gov.noaa.pfel.erddap.dataset.EDDTableFromFiles.fromXml(EDDTableFromFiles.java:467)
 at gov.noaa.pfel.erddap.dataset.EDD.fromXml(EDD.java:422)
 ... 4 more`

However, if I setup the NCEI Trajectory Profile netCDF example by

`wget -qO test.nc https://data.nodc.noaa.gov/thredds/fileServer/example/v2.0/NCEI_trajectoryProfile_template_v2.0_2016-09-22_181838.014029.nc

ncatted -hO -a cdm_data_type,global,m,c,"TrajectoryProfile" test.nc
ncatted -hO -a cdm_trajectory_variables,global,a,c,"trajectory" test.nc
ncatted -hO -a cdm_profile_variables,global,a,c,"time,latitude,longitude" test.nc` 

The ERDDAP server will give me the error message like below...

`*** An error occurred while trying to load NCEI_R4_23e3_15d9_6c01:
java.lang.RuntimeException: datasets.xml error on or before line #287: For cdm_data_type=TrajectoryProfile, one variable must have cf_role=profile_id.
 at gov.noaa.pfel.erddap.dataset.EDD.fromXml(EDD.java:436)
 at gov.noaa.pfel.erddap.dataset.EDD.oneFromDatasetsXml(EDD.java:517)
 at gov.noaa.pfel.erddap.dataset.EDD.testDasDds(EDD.java:11068)
 at gov.noaa.pfel.erddap.DasDds.doIt(DasDds.java:129)
 at gov.noaa.pfel.erddap.DasDds.main(DasDds.java:155)
Caused by: com.cohort.util.SimpleException: For cdm_data_type=TrajectoryProfile, one variable must have cf_role=profile_id.
 at gov.noaa.pfel.erddap.dataset.EDDTable.accessibleViaNcCF(EDDTable.java:12954)
 at gov.noaa.pfel.erddap.dataset.EDD.ensureValid(EDD.java:770)
 at gov.noaa.pfel.erddap.dataset.EDDTable.ensureValid(EDDTable.java:612)
 at gov.noaa.pfel.erddap.dataset.EDDTableFromFiles.<init>(EDDTableFromFiles.java:1839)
 at gov.noaa.pfel.erddap.dataset.EDDTableFromNcFiles.<init>(EDDTableFromNcFiles.java:128)
 at gov.noaa.pfel.erddap.dataset.EDDTableFromFiles.fromXml(EDDTableFromFiles.java:467)
 at gov.noaa.pfel.erddap.dataset.EDD.fromXml(EDD.java:422)
 ... 4 more`

This is because the profile_id is located on the variable "time", but the ERDDAP didn't load **time** variable

`grep sourceName datasets.xml 

        <sourceName>trajectory</sourceName>
        <sourceName>obs</sourceName>
        <sourceName>z</sourceName>
        <sourceName>sal</sourceName>
        <sourceName>temp</sourceName>
        <sourceName>crs</sourceName>`

 Hoping someone here can help me figure this out.

**Comment by cyhsu** [comment]
Yes, I have addressed an issue to the IOOS compliance checker GitHub. Hoping they can solve the standards quickly. 
Following is what the ERDDAP error message from D for if I use "TrajectoryProfile" at ERDDAP. 

Once I feed the netCDF dataset to ERDDAP, I received an error from DasDds.out saying 

`*** An error occurred while trying to load marion_R4_369a_9629_7ce5:
java.lang.RuntimeException: datasets.xml error on or before line #441: For cdm_data_type=TrajectoryProfile, one variable must have cf_role=profile_id.
 at gov.noaa.pfel.erddap.dataset.EDD.fromXml(EDD.java:436)
 at gov.noaa.pfel.erddap.dataset.EDD.oneFromDatasetsXml(EDD.java:517)
 at gov.noaa.pfel.erddap.dataset.EDD.testDasDds(EDD.java:11068)
 at gov.noaa.pfel.erddap.DasDds.doIt(DasDds.java:129)
 at gov.noaa.pfel.erddap.DasDds.main(DasDds.java:155)
Caused by: com.cohort.util.SimpleException: For cdm_data_type=TrajectoryProfile, one variable must have cf_role=profile_id.
 at gov.noaa.pfel.erddap.dataset.EDDTable.accessibleViaNcCF(EDDTable.java:12954)
 at gov.noaa.pfel.erddap.dataset.EDD.ensureValid(EDD.java:770)
 at gov.noaa.pfel.erddap.dataset.EDDTable.ensureValid(EDDTable.java:612)
 at gov.noaa.pfel.erddap.dataset.EDDTableFromFiles.<init>(EDDTableFromFiles.java:1839)
 at gov.noaa.pfel.erddap.dataset.EDDTableFromNcFiles.<init>(EDDTableFromNcFiles.java:128)
 at gov.noaa.pfel.erddap.dataset.EDDTableFromFiles.fromXml(EDDTableFromFiles.java:467)
 at gov.noaa.pfel.erddap.dataset.EDD.fromXml(EDD.java:422)
 ... 4 more`

But in the dataset, I already assigned "**cf_role=profile_id**" to the variable "**time**"  and the variable "time' is not been generated in the XML file. I am looking for what caused this happened. 


Data File: [here](https://drive.google.com/file/d/15sd71p3BlY93O3anvLGkLR2Nca1ghbRN/view?usp=sharing)
DasDds file: [here](https://drive.google.com/file/d/1OQ7fADKxw54Qvhm1_yfphipBnUyNLdPA/view?usp=sharing)
GenerateDatasetsXml.out: [here](https://drive.google.com/file/d/1AFH4FuExIUIwC79Rlqts49Vjf1SVGCiL/view?usp=sharing)

**Comment by BobSimons** [comment]
It is nice that the source file has cf_role=profile_id for the time variable, but if the datasets.xml chunk does not include the time variable, then ERDDAP will never see it.

I see that the dataset type that you selected is EDDTableFromNcFiles.
As the documentation says, for new datasets, please try EDDTableFromMultidimNcFiles instead.

If I use GenerateDatasetsXml with the sample file and seletct EDDTableFromMultidimNcFiles and Sort Files By: time,
then I successfully get a chunk of datasets.xml.
That dataset fails to load in DadDds and ERDDAP because the file has cdm_data_type=Trajectory and other info in the file is consistent with TrajectoryProfile, and because other info needed by ERDDAP is missing. See the requirements at
[](https://coastwatch.pfeg.noaa.gov/erddap/download/setupDatasetsXml.html#cdmTrajectoryProfile)
So if I add to the global <addAttributes>
      <att name="cdm_data_type">TrajectoryProfile</att>
        
        <att name="cdm_trajectory_variables">trajectory, platform, instrument, instrument1</att>
        
        <att name="cdm_profile_variables">time, latitude, longitude, shipHeading, internalInstrumentTemperature, shipZonalVelocity, shipMeridionalVelocity</att>
        
        <att name="subsetVariables">time, latitude, longitude, shipHeading, internalInstrumentTemperature, shipZonalVelocity, shipMeridionalVelocity</att> 
        
        <att name="crs_epsg_code">EPSG:4326</att>
        <att name="crs_longitude_of_prime_meridian" type="double">0.0</att> 
        <att name="crs_semi_major_axis" type="double">6378137.0</att> 
        <att name="crs_inverse_flattening" type="double">298.257223563</att> 
Note that it is common/normal to have to add some of the ERDDAP-specific attributes as <addAttributes>. They don't have to be in the source file.
The resulting chunk of datasets.xml is below.
With those changes, the dataset successfully loads in DasDds and ERDDAP. 

That chunk of datasets.xml isn't perfect, but you can make little changes to the metadata as you see fit. I note that meriodionalVelocity and zonalVelocity both use missing values which are not defined in the metadata. You need to add
    <att name="missing_value" type="double">9.999999680285692E37</att>
to both variables.
Related to that, both of those variables have 
 <att name="FillValue" type="double">-9.99E-29</att>
in the source file. That is doubly incorrect:
  * The CF attribute name you want is "_FillValue", not "FillValue".
  * That value is super close to 0 and seems like it would be in the valid range of values for those variables, so it isn't or shouldn't be used as a _FillValue. I don't know what the correct value should be. If that value was used in the files, then I think the files should be rewritten to use another _FillValue.

I hope that helps.

<dataset type="EDDTableFromMultidimNcFiles" datasetID="hsu" active="true">
    <reloadEveryNMinutes>1440</reloadEveryNMinutes>
    <updateEveryNMillis>10000</updateEveryNMillis>
    <fileDir>/data/hsu/</fileDir>
    <fileNameRegex>.*\.nc</fileNameRegex>
    <recursive>true</recursive>
    <pathRegex>.*</pathRegex>
    <metadataFrom>last</metadataFrom>
    <standardizeWhat>0</standardizeWhat>
    <removeMVRows>true</removeMVRows>
    <sortFilesBySourceNames>time</sortFilesBySourceNames>
    <fileTableInMemory>false</fileTableInMemory>
    
    
    <addAttributes>
        <att name="acknowledgment">null</att>
        <att name="cdm_data_type">TrajectoryProfile</att>
        
        <att name="cdm_trajectory_variables">trajectory, platform, instrument, instrument1</att>
        
        <att name="cdm_profile_variables">time, latitude, longitude, shipHeading, internalInstrumentTemperature, shipZonalVelocity, shipMeridionalVelocity</att>
        
        <att name="subsetVariables">time, latitude, longitude, shipHeading, internalInstrumentTemperature, shipZonalVelocity, shipMeridionalVelocity</att> 
        
        <att name="crs_epsg_code">EPSG:4326</att>
        <att name="crs_longitude_of_prime_meridian" type="double">0.0</att> 
        <att name="crs_semi_major_axis" type="double">6378137.0</att> 
        <att name="crs_inverse_flattening" type="double">298.257223563</att> 

        <att name="contributor_email">null</att>
        <att name="contributor_institution">null</att>
        <att name="contributor_name">null</att>
        <att name="contributor_phone">null</att>
        <att name="contributor_role">null</att>
        <att name="Conventions">CF-1.6, ACDD-1.3, IOOS-1.2, COARDS</att>
        <att name="date_metadata_modified">2020-08-25T17:38:58Z</att>
        <att name="end_time">null</att>
        <att name="infoUrl">https://data.gulfresearchinitiative.org/data/R4.x257.226:0013</att>
        <att name="keywords">-1814142318, 5-18, acoustic, adcp, angle, chemistry, china, circulation, college, component, computer, crs, cruise, current, currents, data, days, decimal, depth, doppler, dp04, earth, Earth Science &gt; Oceans &gt; Ocean Chemistry &gt; Oxygen, Earth Science &gt; Oceans &gt; Ocean Circulation &gt; Ocean Currents, eastward, eastward_sea_water_velocity, flag, good, gulf, gulf of mexico, halmos, heading, identifier, instrument, instrument1, internal, internalInstrumentTemperature, latitude, longitude, meridional, meridionalVelocity, mexico, midas, natural, northern, northward, northward_sea_water_velocity, nova, O2, ocean, oceanography, oceans, oxygen, percent, percent_good, percentGood, platform, platform_eastward_velocity, platform_heading_angle, platform_northward_velocity, point, profiler, quality, quality_flag, r/v, science, sciences, scs, sea, seawater, sensor, serial, serial sensor, ship, ship log, shipboard, shipHeading, shipMeridionalVelocity, shipZonalVelocity, south, southeastern, suite, sur, system, temperature, temperature_of_sensor_for_oxygen_in_sea_water, time, trajectory, tranducer, underway, university, v, velocity, water, zonal, zonalVelocity</att>
        <att name="keywords_vocabulary">GCMD Science Keywords</att>
        <att name="Metadata_Conventions">null</att>
        <att name="ncei_template_version">null</att>
        <att name="sourceUrl">(local files)</att>
        <att name="standard_name_vocabulary">CF Standard Name Table v70</att>
        <att name="start_time">null</att>
        <att name="summary">This dataset contains Acoustic Doppler Current Profiler (ADCP), serial sensor, shipboard computer system (South China Sea (SCS)) measurements, the ship load and cruise track data from aboard the R/V Point Sur for cruise DP04 for an area encompassing roughly 27&#xb0;N to 28&#xb0;N and 86.5&#xb0;W to 90&#xb0;W. Data were collected August 5-18, 2016. The overall purpose of this cruise was to perform deep water sampling of in-situ seawater and associated fauna. description: Shipboard ADCP velocity profiles from PS17_03_Sutton using instrument os75nb</att>
    </addAttributes>
    <dataVariable>
        <sourceName>trajectory</sourceName>
        <destinationName>trajectory</destinationName>
        <dataType>int</dataType>
        
        <addAttributes>
            <att name="_ChunkSizes">null</att>
            <att name="_FillValue" type="int">-2147483647</att>
            <att name="ioos_category">Identifier</att>
            <att name="missing_value" type="int">2147483647</att>
        </addAttributes>
    </dataVariable>
    <dataVariable>
        <sourceName>time</sourceName>
        <destinationName>time</destinationName>
        <dataType>double</dataType>
        
        <addAttributes>
            <att name="_ChunkSizes">null</att>
            <att name="_FillValue" type="double">-9.99E-29</att>
            <att name="ancillary_variables">null</att>
            <att name="cell_method">null</att>
            <att name="colorBarMaximum" type="double">235.0</att>
            <att name="colorBarMinimum" type="double">215.0</att>
            <att name="comment">null</att>
            <att name="coordinates">null</att>
            <att name="FillValue">null</att>
            <att name="grid_mapping">null</att>
            <att name="ioos_category">Time</att>
            <att name="references">null</att>
            <att name="source">null</att>
            <att name="units">days since 2016-01-01T00:00:00Z</att>
        </addAttributes>
    </dataVariable>
    <dataVariable>
        <sourceName>latitude</sourceName>
        <destinationName>latitude</destinationName>
        <dataType>double</dataType>
        
        <addAttributes>
            <att name="_ChunkSizes">null</att>
            <att name="_FillValue" type="double">-9.99E-29</att>
            <att name="ancillary_variables">null</att>
            <att name="colorBarMaximum" type="double">90.0</att>
            <att name="colorBarMinimum" type="double">-90.0</att>
            <att name="comment">null</att>
            <att name="FillValue">null</att>
            <att name="ioos_category">Location</att>
            <att name="long_name">Latitude</att>
        </addAttributes>
    </dataVariable>
    <dataVariable>
        <sourceName>longitude</sourceName>
        <destinationName>longitude</destinationName>
        <dataType>double</dataType>
        
        <addAttributes>
            <att name="_ChunkSizes">null</att>
            <att name="_FillValue" type="double">-9.99E-29</att>
            <att name="ancillary_variables">null</att>
            <att name="colorBarMaximum" type="double">180.0</att>
            <att name="colorBarMinimum" type="double">-180.0</att>
            <att name="comment">null</att>
            <att name="FillValue">null</att>
            <att name="ioos_category">Location</att>
            <att name="long_name">Longitude</att>
        </addAttributes>
    </dataVariable>
    <dataVariable>
        <sourceName>shipHeading</sourceName>
        <destinationName>shipHeading</destinationName>
        <dataType>double</dataType>
        
        <addAttributes>
            <att name="_ChunkSizes">null</att>
            <att name="_FillValue" type="double">-9.99E-29</att>
            <att name="ancillary_variables">null</att>
            <att name="cell_method">null</att>
            <att name="colorBarMaximum" type="double">200.0</att>
            <att name="colorBarMinimum" type="double">-200.0</att>
            <att name="comment">null</att>
            <att name="coordinates">null</att>
            <att name="FillValue">null</att>
            <att name="grid_mapping">null</att>
            <att name="ioos_category">Unknown</att>
            <att name="ncei_name">null</att>
            <att name="references">null</att>
            <att name="source">null</att>
            <att name="units">degrees</att>
        </addAttributes>
    </dataVariable>
    <dataVariable>
        <sourceName>depth</sourceName>
        <destinationName>depth</destinationName>
        <dataType>double</dataType>
        
        <addAttributes>
            <att name="_ChunkSizes">null</att>
            <att name="_FillValue" type="double">-9.99E-29</att>
            <att name="ancillary_variables">null</att>
            <att name="cell_method">null</att>
            <att name="colorBarMaximum" type="double">8000.0</att>
            <att name="colorBarMinimum" type="double">-8000.0</att>
            <att name="colorBarPalette">TopographyDepth</att>
            <att name="comment">null</att>
            <att name="coordinates">null</att>
            <att name="FillValue">null</att>
            <att name="grid_mapping">null</att>
            <att name="ioos_category">Location</att>
            <att name="references">null</att>
            <att name="units">m</att>
        </addAttributes>
    </dataVariable>
    <dataVariable>
        <sourceName>meridionalVelocity</sourceName>
        <destinationName>meridionalVelocity</destinationName>
        <dataType>double</dataType>
        
        <addAttributes>
            <att name="_ChunkSizes">null</att>
            <att name="_FillValue" type="double">-9.99E-29</att>
            <att name="ancillary_variables">null</att>
            <att name="cell_method">null</att>
            <att name="colorBarMaximum" type="double">0.5</att>
            <att name="colorBarMinimum" type="double">-0.5</att>
            <att name="comment">null</att>
            <att name="coordinates">null</att>
            <att name="FillValue">null</att>
            <att name="grid_mapping">null</att>
            <att name="ioos_category">Currents</att>
        </addAttributes>
    </dataVariable>
    <dataVariable>
        <sourceName>zonalVelocity</sourceName>
        <destinationName>zonalVelocity</destinationName>
        <dataType>double</dataType>
        
        <addAttributes>
            <att name="_ChunkSizes">null</att>
            <att name="_FillValue" type="double">-9.99E-29</att>
            <att name="ancillary_variables">null</att>
            <att name="cell_method">null</att>
            <att name="colorBarMaximum" type="double">0.5</att>
            <att name="colorBarMinimum" type="double">-0.5</att>
            <att name="comment">null</att>
            <att name="coordinates">null</att>
            <att name="FillValue">null</att>
            <att name="grid_mapping">null</att>
            <att name="ioos_category">Currents</att>
        </addAttributes>
    </dataVariable>
    <dataVariable>
        <sourceName>percentGood</sourceName>
        <destinationName>percentGood</destinationName>
        <dataType>short</dataType>
        
        <addAttributes>
            <att name="_ChunkSizes">null</att>
            <att name="_FillValue" type="short">0</att>
            <att name="ancillary_variables">null</att>
            <att name="cell_method">null</att>
            <att name="colorBarMaximum" type="double">100.0</att>
            <att name="colorBarMinimum" type="double">0.0</att>
            <att name="comment">null</att>
            <att name="coordinates">null</att>
            <att name="FillValue">null</att>
            <att name="grid_mapping">null</att>
            <att name="ioos_category">Unknown</att>
            <att name="units">percent</att>
        </addAttributes>
    </dataVariable>
    <dataVariable>
        <sourceName>internalInstrumentTemperature</sourceName>
        <destinationName>internalInstrumentTemperature</destinationName>
        <dataType>double</dataType>
        
        <addAttributes>
            <att name="_ChunkSizes">null</att>
            <att name="_FillValue" type="double">-9.99E-29</att>
            <att name="ancillary_variables">null</att>
            <att name="cell_method">null</att>
            <att name="colorBarMaximum" type="double">500.0</att>
            <att name="colorBarMinimum" type="double">0.0</att>
            <att name="comment">null</att>
            <att name="coordinates">null</att>
            <att name="FillValue">null</att>
            <att name="grid_mapping">null</att>
            <att name="ioos_category">Temperature</att>
            <att name="units">degree_C</att>
        </addAttributes>
    </dataVariable>
    <dataVariable>
        <sourceName>shipZonalVelocity</sourceName>
        <destinationName>shipZonalVelocity</destinationName>
        <dataType>double</dataType>
        
        <addAttributes>
            <att name="_ChunkSizes">null</att>
            <att name="_FillValue" type="double">-9.99E-29</att>
            <att name="ancillary_variables">null</att>
            <att name="cell_method">null</att>
            <att name="colorBarMaximum" type="double">1.1999999999999999E38</att>
            <att name="colorBarMinimum" type="double">-2.0E37</att>
            <att name="comment">null</att>
            <att name="coordinates">null</att>
            <att name="FillValue">null</att>
            <att name="grid_mapping">null</att>
            <att name="ioos_category">Currents</att>
            <att name="ncei_name">null</att>
        </addAttributes>
    </dataVariable>
    <dataVariable>
        <sourceName>shipMeridionalVelocity</sourceName>
        <destinationName>shipMeridionalVelocity</destinationName>
        <dataType>double</dataType>
        
        <addAttributes>
            <att name="_ChunkSizes">null</att>
            <att name="_FillValue" type="double">-9.99E-29</att>
            <att name="ancillary_variables">null</att>
            <att name="cell_method">null</att>
            <att name="colorBarMaximum" type="double">1.1999999999999999E38</att>
            <att name="colorBarMinimum" type="double">-2.0E37</att>
            <att name="comment">null</att>
            <att name="coordinates">null</att>
            <att name="FillValue">null</att>
            <att name="grid_mapping">null</att>
            <att name="ioos_category">Currents</att>
            <att name="ncei_name">null</att>
        </addAttributes>
    </dataVariable>
    <dataVariable>
        <sourceName>flag</sourceName>
        <destinationName>flag</destinationName>
        <dataType>short</dataType>
        
        <addAttributes>
            <att name="_ChunkSizes">null</att>
            <att name="_FillValue" type="short">32767</att>
            <att name="colorBarMaximum" type="double">150.0</att>
            <att name="colorBarMinimum" type="double">0.0</att>
            <att name="comment">null</att>
            <att name="coordinates">null</att>
            <att name="FillValue">null</att>
            <att name="grid_mapping">null</att>
            <att name="ioos_category">Quality</att>
            <att name="units">null</att>
        </addAttributes>
    </dataVariable>
    <dataVariable>
        <sourceName>platform</sourceName>
        <destinationName>platform</destinationName>
        <dataType>int</dataType>
        
        <addAttributes>
            <att name="_FillValue" type="int">-2147483647</att>
            <att name="ioos_category">Unknown</att>
            <att name="ioos_code">null</att>
            <att name="missing_value" type="int">2147483647</att>
            <att name="ncei_code">null</att>
        </addAttributes>
    </dataVariable>
    <dataVariable>
        <sourceName>instrument</sourceName>
        <destinationName>instrument</destinationName>
        <dataType>int</dataType>
        
        <addAttributes>
            <att name="_FillValue" type="int">-2147483647</att>
            <att name="calibration_date">null</att>
            <att name="ioos_category">Unknown</att>
            <att name="missing_value" type="int">2147483647</att>
            <att name="serial_number">null</att>
        </addAttributes>
    </dataVariable>
    <dataVariable>
        <sourceName>instrument1</sourceName>
        <destinationName>instrument1</destinationName>
        <dataType>char</dataType>
        
        <addAttributes>
            <att name="calibration_date">null</att>
            <att name="ioos_category">Unknown</att>
            <att name="make_model">null</att>
            <att name="serial_number">null</att>
        </addAttributes>
    </dataVariable>
    <dataVariable>
        <sourceName>crs</sourceName>
        <destinationName>crs</destinationName>
        <dataType>int</dataType>
        
        <addAttributes>
            <att name="_FillValue" type="int">-2147483647</att>
            <att name="ioos_category">Unknown</att>
            <att name="long_name">CRS</att>
            <att name="missing_value" type="int">2147483647</att>
        </addAttributes>
    </dataVariable>
</dataset>

**Comment by cyhsu** [comment]
Thanks Bob, 

I am also thinking of using **EDDTableFromMultidimNcFiles** instead of **EDDTableFromNcFiles** after checking the glider data from Glider DAC OPENDAP, too. After comparing the files, I realized the differences. 

1. NCEI is using **cf_data_type = Trajectory,** while GDAC is using **TrajectoryProfile**
2. NCEI has 2-dimension in time variable, while GDAC has only one.
3. The variable of trajectory in GDAC repeatedly records the glider mission name, while the NCEI has only one 1 record. 

But anyhow, I think the NCEI needs to work on the netCDF template. T**he cdf_data_type = TrajectoryProfile** is way making more sense to me for this type of dataset. 

Follow by your option, I use **NCO** to do some modifications. 

`ncatted -hO -a cdm_data_type,global,m,c,"TrajectoryProfile" test_modified.nc
ncatted -hO -a cdm_trajectory_variables,global,a,c,"trajectory,platform,instrument,instrument1" test_modified.nc
ncatted -hO -a cdm_profile_variables,global,a,c,"time,latitude,longitude,shipHeading,internalInstrumentTemperature,shipZonalVelocity,shipMeridionalVelocity" test_modified.nc
ncatted -hO -a ncei_template_version,global,m,c,"NCEI_NetCDF_TrajectoryProfile_Orthogonal_Template_v2.0" test_modified.nc
ncatted -hO -a featureType,global,m,c,"trajectoryProfile" test_modified.nc
ncrename -hO -a '.FillValue,_FillValue' test_modified.nc`

and it is working.

Thanks!

**Comment by cyhsu** [comment]
Thanks Bob, 

I am also thinking of using **EDDTableFromMultidimNcFiles** instead of **EDDTableFromNcFiles** after checking the glider data from Glider DAC OPENDAP, too. After comparing the files, I realized the differences. 

1. NCEI is using **cf_data_type = Trajectory,** while GDAC is using **TrajectoryProfile**
2. NCEI has 2-dimension in time variable, while GDAC has only one.
3. The variable of trajectory in GDAC repeatedly records the glider mission name, while the NCEI has only one 1 record. 

But anyhow, I think the NCEI needs to work on the netCDF template. T**he cdf_data_type = TrajectoryProfile** is way making more sense to me for this type of dataset. 

Follow by your option, I use **NCO** to do some modifications. 

`ncatted -hO -a cdm_data_type,global,m,c,"TrajectoryProfile" test_modified.nc
ncatted -hO -a cdm_trajectory_variables,global,a,c,"trajectory,platform,instrument,instrument1" test_modified.nc
ncatted -hO -a cdm_profile_variables,global,a,c,"time,latitude,longitude,shipHeading,internalInstrumentTemperature,shipZonalVelocity,shipMeridionalVelocity" test_modified.nc
ncatted -hO -a ncei_template_version,global,m,c,"NCEI_NetCDF_TrajectoryProfile_Orthogonal_Template_v2.0" test_modified.nc
ncatted -hO -a featureType,global,m,c,"trajectoryProfile" test_modified.nc
ncrename -hO -a '.FillValue,_FillValue' test_modified.nc`

and it is working.

Thanks!
