### ISSUE TITLE
Improve how emails are sent

### ISSUE THREAD

**Issue by BobSimons** [BobSimons/erddap#48]
Currently, if ERDDAP needs to send an email, it (in the current thread) connects to the mail server, sends the email, and disconnects. This is inefficient (too much time repeatedly connecting to the server) and slow (it slows down the current thread). Often (e.g., for subscriptions) multiple emails are sent out in a short period of time. 

At the very least, it would be good to have an email queue and dedicate a separate thread to sending emails. There is already a TaskThread, which manages some background tasks (e.g., downloading remote files). There is code to ensure it isn't stalled, recreate it if needed, and stop it when ERDDAP is shutting down. The EmailThread could mimic its system for thread maintenance.

Beyond that, perhaps that thread should be smart about letting emails accumulate in the queue before sending them as a group. For example, perhaps the system should wait 5 (or 10 or ?) seconds after an email is added to the queue in case other emails are also added during that time. Thus, emails would still go out quickly but would be more likely to be sent in a batch rather than individually.

Note that all emails get sent via EDStatic.email(), so it will be easy to modify that to add an email queue.
And the TaskThread has thread management code, so you can just mimic that.

Skills required: Java programming. Since this involves threads, extra care must be taken to avoid problems.

Difficulty: Medium. You'll have to explore JavaMail's features to figure out how to optimize this.  But I think it is a straightforward task. Perhaps 1-2 weeks (after you figure out ERDDAP).

Mentor: Bob Simons (main author of ERDDAP)

Please also read the Programmer's Guide at [https://coastwatch.pfeg.noaa.gov/erddap/download/setup.html#programmersGuide](https://coastwatch.pfeg.noaa.gov/erddap/download/setup.html#programmersGuide)
especially the "Judging Your Code Contributions" section.

**Comment by alyssachne** [comment]
Hi,

I'm a second year computer science student from University of Toronto and I had used Java to write a meeting project. I'm very interested in this topic and I want to work on it. Would you mind giving me a chance to work on it?
(Also I'm currently in my final period, I will work on this start on around April 20th.)

Wish everything goes well for you :)

**Comment by BobSimons** [comment]
Thanks for your interest in working on this project.

If you want to work on it on your own (not as part of Google Summer of Code), then let me know, I'll assign the project to you, and you can work on it in April. 

If you want to be part of GSoC:
My understanding of GSoC (from [https://summerofcode.withgoogle.com/how-it-works/#timeline](https://summerofcode.withgoogle.com/how-it-works/#timeline) )
is that students like you submit applications until Apr 13.
Then we review and select the best student proposals by May 17.
If you are accepted, we "bond" from May 17 - June 7 and actually work on the project together from June 7 to Aug 16.
So, what you can do now is:
  * Read my description of the project carefully. 
    I tried to outline how to approach the project and identify the challenges 
    that must be dealt with.
  * Read, research, and think about how you would do the project so you 
    can include that in your application.
  * Read the Programmer's Guide to ERDDAP that I wrote
    [https://coastwatch.pfeg.noaa.gov/erddap/download/setup.html#programmersGuide](https://coastwatch.pfeg.noaa.gov/erddap/download/setup.html#programmersGuide)
    especially the section at the end on "Judging Your Code Contributions".
  * Get familiar with ERDDAP -- what it is, how it works, how to use it.
  * You can ask me questions about the project publicly via this GitHub Issue 
    or privately via email me (bob dot simons @ noaa dot gov).
  * Submit your GSoC application to Google.
    I've heard that we will only get a few slots for students.

Best wishes.

**Comment by BobSimons** [comment]
I did this. The changes will be in ERDDAP v2.19.
